name: Issue assignment

on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1  # From Github marketplace: https://github.com/marketplace/actions/auto-assign-issue
              with:
                  assignees: juanPabloDiaz
                  numOfAssignee: 1
                  allowSelfAssign: true
