# This workflow uses the lychee-action to check the links
# in your markdown files for validity.
# You can exclude links via a .lycheeignore file in your repository root.
# You find further information about lychee-action in the documentation at:
# https://github.com/lycheeverse/lychee-action

name: Check for broken links

on:
  schedule: # Run every Sunday at 6 am
    - cron: "00 06 * * 0"
  workflow_dispatch:
  # pull_request:
  #   branches: [main]
  # push:
  #   branches: [main]
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          args: README.md
          # args: --verbose --no-progress 'README.md' # for debugging

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "[Bot] Broken Links found (Report)"
          content-filepath: ./lychee/out.md
          labels: broken-link, automated-link-issue
