name: Redeploy on stars.json Update

on:
  push:
    branches: [main]
    paths:
      - 'data/stars.json'
      - '**/stars.json'
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 6" # Run at 12:00 PM every Saturday

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check for stars.json
        id: check_file
        run: |
          if [ -f "data/stars.json" ]; then
            echo "stars_json_exists=true" >> $GITHUB_OUTPUT
          else
            echo "stars_json_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Debug Info
        run: |
          echo "Checking stars.json status:"
          if [ -f "data/stars.json" ]; then
            echo "stars.json exists"
            cat data/stars.json
          else
            echo "stars.json does not exist"
          fi

      - name: Deploy to Vercel
        if: steps.check_file.outputs.stars_json_exists == 'true'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          echo "Starting Vercel deployment..."
          vercel pull --yes --environment=production --token="$VERCEL_TOKEN" --scope="$VERCEL_ORG_ID"
          vercel build --prod --token="$VERCEL_TOKEN"
          vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
