name: Redeploy on stars.json Update

on:
  push:
    branches: [main]
    paths:
      - 'data/stars.json'
      - '**/stars.json'
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 6" # Run at 12:00 PM every Saturday

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check for changes in stars.json
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "stars.json"; then
            echo "stars_json_changed=true" >> $GITHUB_OUTPUT
          else
            echo "stars_json_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Debug Info
        run: |
          echo "Checking for stars.json changes..."
          git diff --name-only HEAD^ HEAD

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          echo "Using Project ID: $VERCEL_PROJECT_ID"
          echo "Using Org ID: $VERCEL_ORG_ID"
          vercel pull --yes --environment=production --token="$VERCEL_TOKEN" --scope="$VERCEL_ORG_ID"
          vercel build --prod --token="$VERCEL_TOKEN"
          vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
