name: Update Stars

on:
  push:
    paths:
      - 'data/stars.json'
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours

jobs:
  update-stars:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for changes in stars.json
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "data/stars.json"; then
            echo "stars_json_changed=true" >> $GITHUB_OUTPUT
          else
            echo "stars_json_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to GitHub Pages
        if: steps.check_changes.outputs.stars_json_changed == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
